#!/bin/bash

usage="Usage: $0 [-t class_template_path | -tf template_folder] class_name ..."
template_folder="$HOME/templates/"
single_template_file=true
template_file="$template_folder/class" # TODO: change this to simple template file name
class_type="class"
file_extension="jr"
#if test "$1"=""
#then
#   echo $usage
#   exit 1
#fi
while getopts "t:tf:mevxh" param
do
   case $param in
         tf) template_folder=$OPTARG;;
         h) echo $usage
         echo
         echo "where"
         echo "-t class_template_path is the class template to use"
         echo "-tf template_folder the path to the folder containing the templates"
         echo "-m for creating a monitor"
         echo "-e for creating a handler of exceptions"
         echo "-v enable verbose mode"
         echo "-x enable debug mode"
         exit 0;;
         e) class_type="handler"
            template_file="$template_folder/handler";;
         m) class_type="monitor"
            file_extension="m"
            template_file="$template_folder/monitor";;
         t) template_file="$template_folder/$OPTARG";;
         v) verbose=true;;
         x) set -x;;
         \?) echo "unknown option"
         echo $usage
         exit 1;;
  esac
done
shift $(($OPTIND-1)) # shifting all the arguments
class_name=$1

if test $single_template_file=true
then
   if test -r "$template_file"
   then 
      cat $template_file | sed -e "s/{{CLASS_NAME}}/$class_name/g" > "$class_name.$file_extension"
   else
      exit 1     
   fi
else
   if test $custom_template_folder=true
   then
      echo "hello"
   fi
fi

if test $class_type = "handler"
then
   stop_exception_handling=true
   while test $stop_exception_handling = true
   do
      read -p "Name of the exception you want to handle:" exception
      echo "   public handler void handle$exception($exception e){" >> "$class_name.$file_extension"
      echo "      // TODO: replace with handle code" >> "$class_name.$file_extension"
      echo "   }" >> "$class_name.$file_extension"
      read -p "Handle another exception ? [Yn]" handle_more
      case $handle_more in
         n) stop_exception_handling=false;;
      esac
  done
  echo "}" >> "$class_name.$file_extension"
  # TODO: replace following block with a template file of the footer
  echo "/*" >> "$class_name.$file_extension"
  echo '** $Log$' >> "$class_name.$file_extension"
  echo "*/" >> "$class_name.$file_extension"
fi
